############# English navigation ##############

# main menu
[[main]]
name = "Kezdőlap"
url = "/"
weight = 1

[[main]]
name = "Projektről"
url = "/about"
weight = 2

[[main]]
name = "Kapcsolat"
url = "/contact"
weight = 3

# footer menu
[[footer]]
name = "Projektről"
url = "/about"
weight = 1

[[footer]]
name = "Adatvédelem"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Sütik"
url = "/cookie-policy"
weight = 3
